# Generated by Django 3.0.4 on 2020-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_attendance_subject_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lecture_date_id', 'student_id')},
        ),
    ]
